import { Router } from 'express';
import dashboardRoutes from './dashboard.js';
import usersRoutes from './users.js';
import auditRoutes from './audit.js';
import inboxRoutes from './inbox.js';
import supportRoutes from './support.js';
import superCodeRoutes from './superCode.js';
import legislatorRequestsRoutes from './legislatorRequests.js';
import activityRoutes from './activity.js';
import notificationsRoutes from './notifications.js';
import emailAdminRoutes from '../../modules/email/email.admin.routes.js';

const router = Router();
router.use('/dashboard', dashboardRoutes);
router.use('/users', usersRoutes);
router.use('/audit', auditRoutes);
router.use('/inbox', inboxRoutes);
router.use('/support', supportRoutes);
router.use('/super-code', superCodeRoutes);
router.use('/legislator-requests', legislatorRequestsRoutes);
router.use('/activity', activityRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/email', emailAdminRoutes);
export default router;
