export const ROUTES = {
  home: "/",
  laws: "/laws",
  subjects: "/subjects",
  search: "/search",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminBilling: "/admin/billing",
  adminAccess: "/admin/access",
  adminCodes: "/admin/codes",
  adminAudit: "/admin/audit",
  adminAnalytics: "/admin/analytics",
  auth: "/auth",
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  account: "/account",
  accountBilling: "/account/billing",
  accountCheckout: "/account/billing/checkout",
  accountSaved: "/account/saved",
  accountNotes: "/account/notes",
  legal: "/legal",
  law: (id: string) => `/laws/${id}`,
  article: (id: string, num: string) => `/laws/${id}/articles/${num}`,
  subject: (id: string) => `/subjects/${id}`,
} as const;
