export const ROUTES = {
  home: "/",
  laws: "/laws",
  analysis: "/analysis",
  projectInfo: "/project-info",
  subjects: "/subjects",
  search: "/search",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminBilling: "/admin/billing",
  adminAccess: "/admin/access",
  adminCodes: "/admin/codes",
  adminAudit: "/admin/audit",
  adminNotifications: "/admin/notifications",
  adminJobs: "/admin/jobs",
  adminDataTools: "/admin/data-tools",
  adminInbox: "/admin/inbox",
  adminSupport: "/admin/support",
  adminAnalytics: "/admin/analytics",
  adminApiCenter: "/admin/api-center",
  adminProjectPage: "/admin/project-page",
  adminArchitecture: "/admin/architecture",
  roadmap: "/roadmap",
  auth: "/auth",
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  authForgotPassword: "/auth/forgot-password",
  authResetPassword: "/auth/reset-password",
  account: "/account",
  accountBilling: "/account/billing",
  accountCheckout: "/account/billing/checkout",
  accountSaved: "/account/saved",
  accountNotes: "/account/notes",
  legal: "/legal",
  law: (id: string) => `/laws/${id}`,
  analysisLaw: (id: string) => `/analysis/laws/${id}`,
  article: (id: string, num: string) => `/laws/${id}/articles/${num}`,
  subject: (id: string) => `/subjects/${id}`,
  assistant: "/assistant",
  help: "/help",
  helpArticle: (slug: string) => `/help/${slug}`,
  adminHelp: "/admin/help",
  adminHelpArticle: (slug: string) => `/admin/help/${slug}`,
  adminEmail: "/admin/email",
  adminEmailCompose: "/admin/email/compose",
  adminEmailTemplates: "/admin/email/templates",
  adminEmailHistory: "/admin/email/history",
  adminEmailSettings: "/admin/email/settings",
  adminEmailSegments: "/admin/email/segments",
  legislatorCabinet: "/legislator-cabinet",
  legislatorCabinetGroups: "/legislator-cabinet/groups",
  legislatorCabinetProposals: "/legislator-cabinet/proposals",
  legislatorCabinetAmendments: "/legislator-cabinet/amendments",
  legislatorCabinetForks: "/legislator-cabinet/forks",
  legislatorCabinetRules: "/legislator-cabinet/rules",
  legislatorCabinetHistory: "/legislator-cabinet/history",
  legislatorCabinetTemplates: "/legislator-cabinet/templates",
  legislatorCabinetChat: "/legislator-cabinet/chat",
  legislatorCabinetChanges: "/legislator-cabinet/changes",
  legislatorCabinetComments: "/legislator-cabinet/comments",
  legislatorCabinetAnalytics: "/legislator-cabinet/analytics",
  legislatorProposal: (id: string) => `/legislator-cabinet/${id}`,
  graph: "/graph",
  radiant: "/radiant",
  support: "/support",
  docs: "/docs",
  roleDashboard: "/role/dashboard",
  rolesDashboard: "/roles/dashboard",
  rolesGuest: "/roles/guest",
  rolesUser: "/roles/user",
  rolesLawmaker: "/roles/lawmaker",
  rolesSupervisor: "/roles/supervisor",
  rolesSupervisorRequest: "/roles/supervisor/request",
  rolesAdmin: "/roles/admin",
  supervisorDashboard: "/supervisor/dashboard",
  supervisorGroups: "/supervisor/groups",
  supervisorProposals: "/supervisor/proposals",
  supervisorAmendments: "/supervisor/amendments",
  supervisorForks: "/supervisor/forks",
  supervisorRules: "/supervisor/rules",
  supervisorHistory: "/supervisor/history",
  supervisorTemplates: "/supervisor/templates",
  supervisorChat: "/supervisor/chat",
  supervisorChanges: "/supervisor/changes",
  supervisorComments: "/supervisor/comments",
  supervisorAnalytics: "/supervisor/analytics",
  supervisorGroup: (id: string) => `/supervisor/groups/${id}`,
  proposals: "/proposals",
  graphProposals: "/graph-proposals",
  radiantProposals: "/radiant-proposals",
} as const;
