export const ROUTES = {
  home: "/",
  laws: "/laws",
  analysis: "/analysis",
  projectInfo: "/project-info",
  subjects: "/subjects",
  search: "/search",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminBilling: "/admin/billing",
  adminAccess: "/admin/access",
  adminCodes: "/admin/codes",
  adminAudit: "/admin/audit",
  adminAnalytics: "/admin/analytics",
  adminProjectPage: "/admin/project-page",
  adminArchitecture: "/admin/architecture",
  roadmap: "/roadmap",
  auth: "/auth",
  authLogin: "/auth/login",
  authRegister: "/auth/register",
  account: "/account",
  accountBilling: "/account/billing",
  accountCheckout: "/account/billing/checkout",
  accountSaved: "/account/saved",
  accountNotes: "/account/notes",
  legal: "/legal",
  law: (id: string) => `/laws/${id}`,
  analysisLaw: (id: string) => `/analysis/laws/${id}`,
  article: (id: string, num: string) => `/laws/${id}/articles/${num}`,
  subject: (id: string) => `/subjects/${id}`,
  assistant: "/assistant",
  help: "/help",
  helpArticle: (slug: string) => `/help/${slug}`,
  adminHelp: "/admin/help",
  adminHelpArticle: (slug: string) => `/admin/help/${slug}`,
  legislatorCabinet: "/legislator-cabinet",
  legislatorProposal: (id: string) => `/legislator-cabinet/${id}`,
} as const;
